# docker compose down -v
# docker compose up -d --build
# http://localhost:8080/swagger
# http://localhost:8080/swagger/v1.0.0.0/swagger.json
# http://localhost:8080/api/vehicles/all
# cd "C:\Users\Pablo\Desktop\Zip Pablo"


# local
# https://localhost:58410/swagger/index.html
# https://localhost:58410/swagger/v1.0.0.0/swagger.json
# http://localhost:58411/swagger/index.html
# http://localhost:58411/swagger/v1.0.0.0/swagger.json

# restore all dotnet prj
# Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
#     dotnet restore $_.FullName
# }

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: hexagonal-sql
    environment:
      SA_PASSWORD: "GTMotive2026!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
        test: ["CMD", "bash", "-c", "pgrep sqlservr"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 20s

  gtmotive.estimate.microservice.host:
    image: ${DOCKER_REGISTRY-}gtmotiveestimatemicroservicehost
    build:
      context: .
      dockerfile: GtMotive.Estimate.Microservice.Host/Dockerfile
    container_name: hexagonal-api
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__HexagonalDb: "Server=sqlserver,1433;Database=HexagonalDb;User Id=sa;Password=GTMotive2026!;Encrypt=False;TrustServerCertificate=True;"
    ports:
      - "8080:8080"

volumes:
  sql_data:



